name: 'GH Environnement variables injector'
description: 'Injects Github environnement variables declared in source files'
inputs:
  override:
    description: 'set to true to override existing workflow variables with definitions from the file(s)'
    required: true
    default: 'true'
  paths:  
    description: 'path to the variable file where the env variables are defined'
    required: true
    default: 'project.vars.properties'
  logs:
    description: 'indicates whenever the action should provide internal logs upon execution'
    required: true
    default: 'false'
branding:
  icon: 'file-text'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.logs }}
    - ${{ inputs.override }}
    - ${{ inputs.paths }}