name: 'GH Environnement variables injector'
description: 'Injects Github environnement variables declared in source files'
inputs:
  logs:  
    description: 'set to 1 to gather internal logs'
    required: true
    default: 'False'
  paths:  
    description: 'path to the variable file where the env variables are defined'
    required: true
    default: 'PROJECTVARS.cfg'
outputs:
  processed: # id of output
    description: 'The file paths that were processed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.paths }}