name: 'GH Environnement variables injector'
description: 'Injects GitHub env variables from files. Supports JSON, Yaml and Plain text formats'
inputs:
  override:
    description: 'set to true to override existing workflow variables with definitions from the file(s)'
    required: true
    default: 'false'
  paths:  
    description: 'path(s) to the file(s) where the variables are defined'
    required: true
    default: 'project.vars.properties'
  select:  
    description: 'list of variables to import, when empty import all discovered variables'
    required: true
    default: ''
branding:
  icon: 'file-text'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - override=${{ inputs.override }}
    - paths=${{ inputs.paths }}
    - select=${{ inputs.select }}
