name: 'GH Environnement variables injector'
description: 'Injects GH environnement variables declared in a file '
inputs:
  paths:  # id of input
    description: 'path to the variable file where the env variables are defined'
    required: true
    default: 'PROJECTVARS.cfg'
outputs:
  processed: # id of output
    description: 'The file paths that were processed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.paths }}