name: tests the github varfiletoenv action

on:
  push:
    branches: [ "topython" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "topython" ]
    paths-ignore:
      - 'README.md'
 
permissions:
  contents: read

jobs:
  build-python:
    
    runs-on: ubuntu-latest
    
    env:
      PYTHON_VERSION: 3.8

    steps:


    - name: Setup Python ${{ env.PYTHON_VERSION }} interpreter
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}


    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Ensure all sources in Unix format
      run: |
        sudo apt-get install -y dos2unix
        find . -type f -name "*.py" | xargs dos2unix

    - name: Setup Python dependency modules
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi