# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test action 42

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
 
permissions:
  contents: read

jobs:
  test:
    
    runs-on: ubuntu-latest
    env:
      Trumpet: Freddy.Hubbard
      TheBoss: Miles Davis

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Import project variables
      uses: zlatko-ms/varfiletoenv@v1
      with:
        varfilepath: ./test/projectvars.properties

    - name: Ensure variables defined 
      run: |
        function assertDefinedAndEqualTo() {  
          
          name=$1
          expected=$2
          
          if [ -z "${!name}" ] ; then
            echo "[ERROR] variable $name is not defined";
            exit 255;
          fi
          
          if [ "${!name}" != "$expected" ] ; then 
            echo "[ERROR] variable $name , expected=$expected provided=${!name}";
            exit 255;
          fi
          
        }
        
        # Test workflow defined variable
        assertDefinedAndEqualTo "TheBoss" "Miles Davis"
        
        # Test file injected variables
        assertDefinedAndEqualTo "theCommander" "John Coltrane"
        assertDefinedAndEqualTo "RELEASE" "1.2.3"
        assertDefinedAndEqualTo "myFavorite" "Things"
        
        # Test local variable overriden from file
        assertDefinedAndEqualTo "Trumpet" "Miles Davis"
      
        