# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test action 42

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
 
permissions:
  contents: read

jobs:
  test:
    
    runs-on: ubuntu-latest
    env:
      Trumpet: Freddy.Hubbard
      TheBoss: Miles Davis

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Import project variables without overriding
      uses: zlatko-ms/varfiletoenv@2-add-support-for-override-flag
      with:
        override: false
        paths: |
          ./test/projectvars.properties
          ./test/release.properties
          ./test/override.properties
          ./test/nonexistingfile.properties
        
    - name: Ensure variables are defined from file 
      run: |
        # source the assertion shell function
        source ./test/vartestfunction.sh
        
        # Test workflow defined variable
        assertDefinedAndEqualTo "TheBoss" "Miles Davis"
        
        # Test file injected variables
        assertDefinedAndEqualTo "theCommander" "John Coltrane"
        assertDefinedAndEqualTo "RELEASE" "1.2.3"
        assertDefinedAndEqualTo "myFavorite" "Things"
        
        # Test local variable overriden from file
        #assertDefinedAndEqualTo "Trumpet" "Miles Davis"

    - name: Import project variables without overriding
      uses: zlatko-ms/varfiletoenv@2-add-support-for-override-flag
      with:
        override: true
        paths: |
          ./test/override.properties

    - name: Ensure variables are overidden from file 
      run: |
        # source the assertion shell function
        source ./test/vartestfunction.sh
        # perform assertions
        assertDefinedAndEqualTo "Trumpet" "Miles Davis"
      
        